//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.Resources.Languages.ProductDetail {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProductDetail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductDetail() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ECommerce.Resources.Languages.ProductDetail.ProductDetail", typeof(ProductDetail).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHI TIẾT SẢN PHẨM.
        /// </summary>
        public static string CHI_TIET_SAN_PHAM {
            get {
                return ResourceManager.GetString("CHI_TIET_SAN_PHAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHÍNH SÁCH VÀ QUYỀN LỢI.
        /// </summary>
        public static string CHINH_SACH_VA_QUYEN_LOI {
            get {
                return ResourceManager.GetString("CHINH_SACH_VA_QUYEN_LOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CÓ THỂ BẠN THÍCH.
        /// </summary>
        public static string CO_THE_BAN_THICH {
            get {
                return ResourceManager.GetString("CO_THE_BAN_THICH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặc tính.
        /// </summary>
        public static string DAC_TINH {
            get {
                return ResourceManager.GetString("DAC_TINH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ĐÁNH GIÁ.
        /// </summary>
        public static string DANH_GIA {
            get {
                return ResourceManager.GetString("DANH_GIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục khác.
        /// </summary>
        public static string DANH_MUC_KHAC {
            get {
                return ResourceManager.GetString("DANH_MUC_KHAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SẢN PHẨM MỚI CÙNG LOẠI.
        /// </summary>
        public static string SAN_PHAM_MOI_CUNG_LOAI {
            get {
                return ResourceManager.GetString("SAN_PHAM_MOI_CUNG_LOAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SẢN PHẨM TƯƠNG TỰ.
        /// </summary>
        public static string SAN_PHAM_TUONG_TU {
            get {
                return ResourceManager.GetString("SAN_PHAM_TUONG_TU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THÔNG SỐ SẢN PHẨM.
        /// </summary>
        public static string THONG_SO_SAN_PHAM {
            get {
                return ResourceManager.GetString("THONG_SO_SAN_PHAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin.
        /// </summary>
        public static string THONG_TIN {
            get {
                return ResourceManager.GetString("THONG_TIN", resourceCulture);
            }
        }
    }
}
