SET IDENTITY_INSERT Citys OFF
SET IDENTITY_INSERT Districts ON
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (1,N'Quận Ba Đình',2,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (2,N'Quận Hoàn Kiếm',2,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (3,N'Quận Tây Hồ',2,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (4,N'Quận Long Biên',2,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (5,N'Quận Cầu Giấy',2,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (6,N'Quận Đống Đa',2,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (7,N'Quận Hai Bà Trưng',2,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (8,N'Quận Hoàng Mai',2,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (9,N'Quận Thanh Xuân',2,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (16,N'Huyện Sóc Sơn',2,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (17,N'Huyện Đông Anh',2,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (18,N'Huyện Gia Lâm',2,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (19,N'Quận Nam Từ Liêm',2,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (20,N'Huyện Thanh Trì',2,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (21,N'Quận Bắc Từ Liêm',2,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (24,N'Thành phố Hà Giang',17,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (26,N'Huyện Đồng Văn',17,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (27,N'Huyện Mèo Vạc',17,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (28,N'Huyện Yên Minh',17,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (29,N'Huyện Quản Bạ',17,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (30,N'Huyện Vị Xuyên',17,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (31,N'Huyện Bắc Mê',17,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (32,N'Huyện Hoàng Su Phì',17,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (33,N'Huyện Xín Mần',17,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (34,N'Huyện Bắc Quang',17,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (35,N'Huyện Quang Bình',17,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (40,N'Thành phố Cao Bằng',15,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (42,N'Huyện Bảo Lâm',15,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (43,N'Huyện Bảo Lạc',15,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (44,N'Huyện Thông Nông',15,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (45,N'Huyện Hà Quảng',15,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (46,N'Huyện Trà Lĩnh',15,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (47,N'Huyện Trùng Khánh',15,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (48,N'Huyện Hạ Lang',15,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (49,N'Huyện Quảng Uyên',15,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (50,N'Huyện Phục Hòa',15,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (51,N'Huyện Hòa An',15,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (52,N'Huyện Nguyên Bình',15,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (53,N'Huyện Thạch An',15,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (58,N'Thành Phố Bắc Kạn',6,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (60,N'Huyện Pác Nặm',6,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (61,N'Huyện Ba Bể',6,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (62,N'Huyện Ngân Sơn',6,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (63,N'Huyện Bạch Thông',6,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (64,N'Huyện Chợ Đồn',6,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (65,N'Huyện Chợ Mới',6,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (66,N'Huyện Na Rì',6,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (70,N'Thành phố Tuyên Quang',52,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (71,N'Huyện Lâm Bình',52,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (72,N'Huyện Na Hang',52,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (73,N'Huyện Chiêm Hóa',52,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (74,N'Huyện Hàm Yên',52,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (75,N'Huyện Yên Sơn',52,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (76,N'Huyện Sơn Dương',52,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (80,N'Thành phố Lào Cai',31,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (82,N'Huyện Bát Xát',31,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (83,N'Huyện Mường Khương',31,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (84,N'Huyện Si Ma Cai',31,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (85,N'Huyện Bắc Hà',31,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (86,N'Huyện Bảo Thắng',31,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (87,N'Huyện Bảo Yên',31,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (88,N'Huyện Sa Pa',31,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (89,N'Huyện Văn Bàn',31,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (94,N'Thành phố Điện Biên Phủ',59,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (95,N'Thị Xã Mường Lay',59,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (96,N'Huyện Mường Nhé',59,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (97,N'Huyện Mường Chà',59,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (98,N'Huyện Tủa Chùa',59,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (99,N'Huyện Tuần Giáo',59,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (100,N'Huyện Điện Biên',59,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (101,N'Huyện Điện Biên Đông',59,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (102,N'Huyện Mường Ảng',59,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (103,N'Huyện Nậm Pồ',59,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (105,N'Thành phố Lai Châu',28,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (106,N'Huyện Tam Đường',28,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (107,N'Huyện Mường Tè',28,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (108,N'Huyện Sìn Hồ',28,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (109,N'Huyện Phong Thổ',28,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (110,N'Huyện Than Uyên',28,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (111,N'Huyện Tân Uyên',28,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (112,N'Huyện Nậm Nhùn',28,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (116,N'Thành phố Sơn La',45,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (118,N'Huyện Quỳnh Nhai',45,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (119,N'Huyện Thuận Châu',45,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (120,N'Huyện Mường La',45,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (121,N'Huyện Bắc Yên',45,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (122,N'Huyện Phù Yên',45,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (123,N'Huyện Mộc Châu',45,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (124,N'Huyện Yên Châu',45,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (125,N'Huyện Mai Sơn',45,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (126,N'Huyện Sông Mã',45,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (127,N'Huyện Sốp Cộp',45,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (128,N'Huyện Vân Hồ',45,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (132,N'Thành phố Yên Bái',55,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (133,N'Thị xã Nghĩa Lộ',55,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (135,N'Huyện Lục Yên',55,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (136,N'Huyện Văn Yên',55,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (137,N'Huyện Mù Căng Chải',55,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (138,N'Huyện Trấn Yên',55,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (139,N'Huyện Trạm Tấu',55,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (140,N'Huyện Văn Chấn',55,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (141,N'Huyện Yên Bình',55,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (148,N'Thành phố Hòa Bình',23,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (150,N'Huyện Đà Bắc',23,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (151,N'Huyện Kỳ Sơn',23,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (152,N'Huyện Lương Sơn',23,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (153,N'Huyện Kim Bôi',23,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (154,N'Huyện Cao Phong',23,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (155,N'Huyện Tân Lạc',23,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (156,N'Huyện Mai Châu',23,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (157,N'Huyện Lạc Sơn',23,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (158,N'Huyện Yên Thủy',23,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (159,N'Huyện Lạc Thủy',23,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (164,N'Thành phố Thái Nguyên',48,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (165,N'Thành phố Sông Công',48,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (167,N'Huyện Định Hóa',48,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (168,N'Huyện Phú Lương',48,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (169,N'Huyện Đồng Hỷ',48,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (170,N'Huyện Võ Nhai',48,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (171,N'Huyện Đại Từ',48,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (172,N'Thị xã Phổ Yên',48,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (173,N'Huyện Phú Bình',48,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (178,N'Thành phố Lạng Sơn',30,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (180,N'Huyện Tràng Định',30,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (181,N'Huyện Bình Gia',30,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (182,N'Huyện Văn Lãng',30,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (183,N'Huyện Cao Lộc',30,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (184,N'Huyện Văn Quan',30,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (185,N'Huyện Bắc Sơn',30,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (186,N'Huyện Hữu Lũng',30,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (187,N'Huyện Chi Lăng',30,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (188,N'Huyện Lộc Bình',30,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (189,N'Huyện Đình Lập',30,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (193,N'Thành phố Hạ Long',42,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (194,N'Thành phố Móng Cái',42,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (195,N'Thành phố Cẩm Phả',42,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (196,N'Thành phố Uông Bí',42,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (198,N'Huyện Bình Liêu',42,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (199,N'Huyện Tiên Yên',42,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (200,N'Huyện Đầm Hà',42,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (201,N'Huyện Hải Hà',42,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (202,N'Huyện Ba Chẽ',42,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (203,N'Huyện Vân Đồn',42,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (204,N'Huyện Hoành Bồ',42,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (205,N'Thị xã Đông Triều',42,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (206,N'Thị xã Quảng Yên',42,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (207,N'Huyện Cô Tô',42,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (213,N'Thành phố Bắc Giang',5,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (215,N'Huyện Yên Thế',5,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (216,N'Huyện Tân Yên',5,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (217,N'Huyện Lạng Giang',5,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (218,N'Huyện Lục Nam',5,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (219,N'Huyện Lục Ngạn',5,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (220,N'Huyện Sơn Động',5,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (221,N'Huyện Yên Dũng',5,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (222,N'Huyện Việt Yên',5,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (223,N'Huyện Hiệp Hòa',5,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (227,N'Thành phố Việt Trì',37,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (228,N'Thị xã Phú Thọ',37,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (230,N'Huyện Đoan Hùng',37,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (231,N'Huyện Hạ Hòa',37,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (232,N'Huyện Thanh Ba',37,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (233,N'Huyện Phù Ninh',37,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (234,N'Huyện Yên Lập',37,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (235,N'Huyện Cẩm Khê',37,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (236,N'Huyện Tam Nông',37,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (237,N'Huyện Lâm Thao',37,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (238,N'Huyện Thanh Sơn',37,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (239,N'Huyện Thanh Thuỷ',37,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (240,N'Huyện Tân Sơn',37,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (243,N'Thành phố Vĩnh Yên',54,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (244,N'Thị xã Phúc Yên',54,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (246,N'Huyện Lập Thạch',54,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (247,N'Huyện Tam Dương',54,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (248,N'Huyện Tam Đảo',54,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (249,N'Huyện Bình Xuyên',54,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (250,N'Huyện Mê Linh',2,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (251,N'Huyện Yên Lạc',54,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (252,N'Huyện Vĩnh Tường',54,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (253,N'Huyện Sông Lô',54,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (256,N'Thành phố Bắc Ninh',8,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (258,N'Huyện Yên Phong',8,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (259,N'Huyện Quế Võ',8,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (260,N'Huyện Tiên Du',8,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (261,N'Thị xã Từ Sơn',8,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (262,N'Huyện Thuận Thành',8,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (263,N'Huyện Gia Bình',8,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (264,N'Huyện Lương Tài',8,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (268,N'Quận Hà Đông',2,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (269,N'Thị xã Sơn Tây',2,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (271,N'Huyện Ba Vì',2,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (272,N'Huyện Phúc Thọ',2,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (273,N'Huyện Đan Phượng',2,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (274,N'Huyện Hoài Đức',2,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (275,N'Huyện Quốc Oai',2,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (276,N'Huyện Thạch Thất',2,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (277,N'Huyện Chương Mỹ',2,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (278,N'Huyện Thanh Oai',2,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (279,N'Huyện Thường Tín',2,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (280,N'Huyện Phú Xuyên',2,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (281,N'Huyện Ứng Hòa',2,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (282,N'Huyện Mỹ Đức',2,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (288,N'Thành phố Hải Dương',20,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (290,N'Thị xã Chí Linh',20,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (291,N'Huyện Nam Sách',20,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (292,N'Huyện Kinh Môn',20,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (293,N'Huyện Kim Thành',20,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (294,N'Huyện Thanh Hà',20,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (295,N'Huyện Cẩm Giàng',20,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (296,N'Huyện Bình Giang',20,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (297,N'Huyện Gia Lộc',20,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (298,N'Huyện Tứ Kỳ',20,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (299,N'Huyện Ninh Giang',20,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (300,N'Huyện Thanh Miện',20,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (303,N'Quận Hồng Bàng',21,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (304,N'Quận Ngô Quyền',21,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (305,N'Quận Lê Chân',21,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (306,N'Quận Hải An',21,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (307,N'Quận Kiến An',21,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (308,N'Quận Đồ Sơn',21,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (309,N'Quận Dương Kinh',21,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (311,N'Huyện Thủy Nguyên',21,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (312,N'Huyện An Dương',21,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (313,N'Huyện An Lão',21,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (314,N'Huyện Kiến Thuỵ',21,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (315,N'Huyện Tiên Lãng',21,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (316,N'Huyện Vĩnh Bảo',21,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (317,N'Huyện Cát Hải',21,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (318,N'Huyện Bạch Long Vĩ',21,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (323,N'Thành phố Hưng Yên',24,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (325,N'Huyện Văn Lâm',24,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (326,N'Huyện Văn Giang',24,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (327,N'Huyện Yên Mỹ',24,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (328,N'Huyện Mỹ Hào',24,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (329,N'Huyện Ân Thi',24,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (330,N'Huyện Khoái Châu',24,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (331,N'Huyện Kim Động',24,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (332,N'Huyện Tiên Lữ',24,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (333,N'Huyện Phù Cừ',24,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (336,N'Thành phố Thái Bình',47,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (338,N'Huyện Quỳnh Phụ',47,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (339,N'Huyện Hưng Hà',47,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (340,N'Huyện Đông Hưng',47,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (341,N'Huyện Thái Thụy',47,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (342,N'Huyện Tiền Hải',47,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (343,N'Huyện Kiến Xương',47,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (344,N'Huyện Vũ Thư',47,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (347,N'Thành phố Phủ Lý',18,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (349,N'Huyện Duy Tiên',18,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (350,N'Huyện Kim Bảng',18,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (351,N'Huyện Thanh Liêm',18,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (352,N'Huyện Bình Lục',18,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (353,N'Huyện Lý Nhân',18,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (356,N'Thành phố Nam Định',33,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (358,N'Huyện Mỹ Lộc',33,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (359,N'Huyện Vụ Bản',33,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (360,N'Huyện Ý Yên',33,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (361,N'Huyện Nghĩa Hưng',33,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (362,N'Huyện Nam Trực',33,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (363,N'Huyện Trực Ninh',33,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (364,N'Huyện Xuân Trường',33,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (365,N'Huyện Giao Thủy',33,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (366,N'Huyện Hải Hậu',33,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (369,N'Thành phố Ninh Bình',35,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (370,N'Thành phố Tam Điệp',35,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (372,N'Huyện Nho Quan',35,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (373,N'Huyện Gia Viễn',35,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (374,N'Huyện Hoa Lư',35,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (375,N'Huyện Yên Khánh',35,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (376,N'Huyện Kim Sơn',35,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (377,N'Huyện Yên Mô',35,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (380,N'Thành phố Thanh Hóa',49,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (381,N'Thị xã Bỉm Sơn',49,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (382,N'Thành phố Sầm Sơn',49,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (384,N'Huyện Mường Lát',49,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (385,N'Huyện Quan Hóa',49,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (386,N'Huyện Bá Thước',49,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (387,N'Huyện Quan Sơn',49,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (388,N'Huyện Lang Chánh',49,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (389,N'Huyện Ngọc Lặc',49,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (390,N'Huyện Cẩm Thủy',49,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (391,N'Huyện Thạch Thành',49,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (392,N'Huyện Hà Trung',49,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (393,N'Huyện Vĩnh Lộc',49,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (394,N'Huyện Yên Định',49,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (395,N'Huyện Thọ Xuân',49,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (396,N'Huyện Thường Xuân',49,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (397,N'Huyện Triệu Sơn',49,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (398,N'Huyện Thiệu Hóa',49,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (399,N'Huyện Hoằng Hóa',49,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (400,N'Huyện Hậu Lộc',49,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (401,N'Huyện Nga Sơn',49,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (402,N'Huyện Như Xuân',49,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (403,N'Huyện Như Thanh',49,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (404,N'Huyện Nông Cống',49,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (405,N'Huyện Đông Sơn',49,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (406,N'Huyện Quảng Xương',49,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (407,N'Huyện Tĩnh Gia',49,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (412,N'Thành phố Vinh',34,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (413,N'Thị xã Cửa Lò',34,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (414,N'Thị xã Thái Hòa',34,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (415,N'Huyện Quế Phong',34,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (416,N'Huyện Quỳ Châu',34,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (417,N'Huyện Kỳ Sơn',34,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (418,N'Huyện Tương Dương',34,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (419,N'Huyện Nghĩa Đàn',34,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (420,N'Huyện Quỳ Hợp',34,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (421,N'Huyện Quỳnh Lưu',34,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (422,N'Huyện Con Cuông',34,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (423,N'Huyện Tân Kỳ',34,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (424,N'Huyện Anh Sơn',34,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (425,N'Huyện Diễn Châu',34,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (426,N'Huyện Yên Thành',34,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (427,N'Huyện Đô Lương',34,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (428,N'Huyện Thanh Chương',34,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (429,N'Huyện Nghi Lộc',34,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (430,N'Huyện Nam Đàn',34,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (431,N'Huyện Hưng Nguyên',34,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (432,N'Thị xã Hoàng Mai',34,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (436,N'Thành phố Hà Tĩnh',19,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (437,N'Thị xã Hồng Lĩnh',19,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (439,N'Huyện Hương Sơn',19,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (440,N'Huyện Đức Thọ',19,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (441,N'Huyện Vũ Quang',19,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (442,N'Huyện Nghi Xuân',19,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (443,N'Huyện Can Lộc',19,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (444,N'Huyện Hương Khê',19,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (445,N'Huyện Thạch Hà',19,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (446,N'Huyện Cẩm Xuyên',19,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (447,N'Huyện Kỳ Anh',19,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (448,N'Huyện Lộc Hà',19,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (449,N'Thị xã Kỳ Anh',19,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (450,N'Thành Phố Đồng Hới',39,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (452,N'Huyện Minh Hóa',39,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (453,N'Huyện Tuyên Hóa',39,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (454,N'Huyện Quảng Trạch',39,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (455,N'Huyện Bố Trạch',39,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (456,N'Huyện Quảng Ninh',39,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (457,N'Huyện Lệ Thủy',39,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (458,N'Thị xã Ba Đồn',39,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (461,N'Thành phố Đông Hà',43,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (462,N'Thị xã Quảng Trị',43,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (464,N'Huyện Vĩnh Linh',43,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (465,N'Huyện Hướng Hóa',43,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (466,N'Huyện Gio Linh',43,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (467,N'Huyện Đakrông',43,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (468,N'Huyện Cam Lộ',43,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (469,N'Huyện Triệu Phong',43,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (470,N'Huyện Hải Lăng',43,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (474,N'Thành phố Huế',64,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (476,N'Huyện Phong Điền',64,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (477,N'Huyện Quảng Điền',64,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (478,N'Huyện Phú Vang',64,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (479,N'Thị xã Hương Thủy',64,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (480,N'Thị xã Hương Trà',64,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (481,N'Huyện A Lưới',64,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (482,N'Huyện Phú Lộc',64,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (483,N'Huyện Nam Đông',64,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (490,N'Quận Liên Chiểu',56,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (491,N'Quận Thanh Khê',56,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (492,N'Quận Hải Châu',56,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (493,N'Quận Sơn Trà',56,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (494,N'Quận Ngũ Hành Sơn',56,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (495,N'Quận Cẩm Lệ',56,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (497,N'Huyện Hòa Vang',56,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (502,N'Thành phố Tam Kỳ',40,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (503,N'Thành phố Hội An',40,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (504,N'Huyện Tây Giang',40,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (505,N'Huyện Đông Giang',40,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (506,N'Huyện Đại Lộc',40,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (507,N'Thị xã Điện Bàn',40,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (508,N'Huyện Duy Xuyên',40,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (509,N'Huyện Quế Sơn',40,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (510,N'Huyện Nam Giang',40,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (511,N'Huyện Phước Sơn',40,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (512,N'Huyện Hiệp Đức',40,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (513,N'Huyện Thăng Bình',40,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (514,N'Huyện Tiên Phước',40,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (515,N'Huyện Bắc Trà My',40,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (516,N'Huyện Nam Trà My',40,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (517,N'Huyện Núi Thành',40,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (518,N'Huyện Phú Ninh',40,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (519,N'Huyện Nông Sơn',40,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (522,N'Thành phố Quảng Ngãi',41,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (524,N'Huyện Bình Sơn',41,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (525,N'Huyện Trà Bồng',41,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (526,N'Huyện Tây Trà',41,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (527,N'Huyện Sơn Tịnh',41,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (528,N'Huyện Tư Nghĩa',41,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (529,N'Huyện Sơn Hà',41,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (530,N'Huyện Sơn Tây',41,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (531,N'Huyện Minh Long',41,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (532,N'Huyện Nghĩa Hành',41,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (533,N'Huyện Mộ Đức',41,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (534,N'Huyện Đức Phổ',41,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (535,N'Huyện Ba Tơ',41,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (536,N'Huyện Lý Sơn',41,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (540,N'Thành phố Quy Nhơn',12,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (542,N'Huyện An Lão',12,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (543,N'Huyện Hoài Nhơn',12,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (544,N'Huyện Hoài Ân',12,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (545,N'Huyện Phù Mỹ',12,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (546,N'Huyện Vĩnh Thạnh',12,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (547,N'Huyện Tây Sơn',12,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (548,N'Huyện Phù Cát',12,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (549,N'Thị xã An Nhơn',12,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (550,N'Huyện Tuy Phước',12,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (551,N'Huyện Vân Canh',12,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (555,N'Thành phố Tuy Hòa',38,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (557,N'Thị xã Sông Cầu',38,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (558,N'Huyện Đồng Xuân',38,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (559,N'Huyện Tuy An',38,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (560,N'Huyện Sơn Hòa',38,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (561,N'Huyện Sông Hinh',38,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (562,N'Huyện Tây Hòa',38,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (563,N'Huyện Phú Hòa',38,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (564,N'Huyện Đông Hòa',38,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (568,N'Thành phố Nha Trang',25,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (569,N'Thành phố Cam Ranh',25,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (570,N'Huyện Cam Lâm',25,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (571,N'Huyện Vạn Ninh',25,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (572,N'Thị xã Ninh Hòa',25,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (573,N'Huyện Khánh Vĩnh',25,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (574,N'Huyện Diên Khánh',25,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (575,N'Huyện Khánh Sơn',25,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (576,N'Huyện Trường Sa',25,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (582,N'Thành phố Phan Rang-Tháp Chàm',36,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (584,N'Huyện Bác Ái',36,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (585,N'Huyện Ninh Sơn',36,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (586,N'Huyện Ninh Hải',36,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (587,N'Huyện Ninh Phước',36,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (588,N'Huyện Thuận Bắc',36,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (589,N'Huyện Thuận Nam',36,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (593,N'Thành phố Phan Thiết',11,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (594,N'Thị xã La Gi',11,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (595,N'Huyện Tuy Phong',11,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (596,N'Huyện Bắc Bình',11,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (597,N'Huyện Hàm Thuận Bắc',11,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (598,N'Huyện Hàm Thuận Nam',11,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (599,N'Huyện Tánh Linh',11,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (600,N'Huyện Đức Linh',11,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (601,N'Huyện Hàm Tân',11,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (602,N'Huyện Phú Quí',11,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (608,N'Thành phố Kon Tum',27,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (610,N'Huyện Đắk Glei',27,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (611,N'Huyện Ngọc Hồi',27,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (612,N'Huyện Đắk Tô',27,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (613,N'Huyện Kon Plông',27,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (614,N'Huyện Kon Rẫy',27,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (615,N'Huyện Đắk Hà',27,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (616,N'Huyện Sa Thầy',27,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (617,N'Huyện Tu Mơ Rông',27,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (618,N'Huyện Ia H" Drai',27,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (622,N'Thành phố Pleiku',16,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (623,N'Thị xã An Khê',16,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (624,N'Thị xã Ayun Pa',16,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (625,N'Huyện KBang',16,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (626,N'Huyện Đăk Đoa',16,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (627,N'Huyện Chư Păh',16,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (628,N'Huyện Ia Grai',16,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (629,N'Huyện Mang Yang',16,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (630,N'Huyện Kông Chro',16,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (631,N'Huyện Đức Cơ',16,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (632,N'Huyện Chư Prông',16,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (633,N'Huyện Chư Sê',16,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (634,N'Huyện Đăk Pơ',16,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (635,N'Huyện Ia Pa',16,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (637,N'Huyện Krông Pa',16,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (638,N'Huyện Phú Thiện',16,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (639,N'Huyện Chư Pưh',16,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (643,N'Thành phố Buôn Ma Thuột',57,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (644,N'Thị Xã Buôn Hồ',57,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (645,N'Huyện Ea H"leo',57,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (646,N'Huyện Ea Súp',57,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (647,N'Huyện Buôn Đôn',57,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (648,N'Huyện Cư M"gar',57,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (649,N'Huyện Krông Búk',57,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (650,N'Huyện Krông Năng',57,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (651,N'Huyện Ea Kar',57,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (652,N'Huyện M"Đrắk',57,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (653,N'Huyện Krông Bông',57,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (654,N'Huyện Krông Pắc',57,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (655,N'Huyện Krông A Na',57,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (656,N'Huyện Lắk',57,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (657,N'Huyện Cư Kuin',57,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (660,N'Thị xã Gia Nghĩa',58,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (661,N'Huyện Đăk Glong',58,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (662,N'Huyện Cư Jút',58,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (663,N'Huyện Đắk Mil',58,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (664,N'Huyện Krông Nô',58,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (665,N'Huyện Đắk Song',58,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (666,N'Huyện Đắk R"Lấp',58,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (667,N'Huyện Tuy Đức',58,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (672,N'Thành phố Đà Lạt',29,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (673,N'Thành phố Bảo Lộc',29,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (674,N'Huyện Đam Rông',29,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (675,N'Huyện Lạc Dương',29,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (676,N'Huyện Lâm Hà',29,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (677,N'Huyện Đơn Dương',29,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (678,N'Huyện Đức Trọng',29,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (679,N'Huyện Di Linh',29,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (680,N'Huyện Bảo Lâm',29,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (681,N'Huyện Đạ Huoai',29,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (682,N'Huyện Đạ Tẻh',29,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (683,N'Huyện Cát Tiên',29,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (688,N'Thị xã Phước Long',10,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (689,N'Thị xã Đồng Xoài',10,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (690,N'Thị xã Bình Long',10,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (691,N'Huyện Bù Gia Mập',10,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (692,N'Huyện Lộc Ninh',10,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (693,N'Huyện Bù Đốp',10,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (694,N'Huyện Hớn Quản',10,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (695,N'Huyện Đồng Phú',10,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (696,N'Huyện Bù Đăng',10,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (697,N'Huyện Chơn Thành',10,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (698,N'Huyện Phú Riềng',10,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (703,N'Thành phố Tây Ninh',46,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (705,N'Huyện Tân Biên',46,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (706,N'Huyện Tân Châu',46,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (707,N'Huyện Dương Minh Châu',46,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (708,N'Huyện Châu Thành',46,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (709,N'Huyện Hòa Thành',46,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (710,N'Huyện Gò Dầu',46,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (711,N'Huyện Bến Cầu',46,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (712,N'Huyện Trảng Bàng',46,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (718,N'Thành phố Thủ Dầu Một',9,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (719,N'Huyện Bàu Bàng',9,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (720,N'Huyện Dầu Tiếng',9,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (721,N'Thị xã Bến Cát',9,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (722,N'Huyện Phú Giáo',9,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (723,N'Thị xã Tân Uyên',9,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (724,N'Thị xã Dĩ An',9,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (725,N'Thị xã Thuận An',9,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (726,N'Huyện Bắc Tân Uyên',9,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (731,N'Thành phố Biên Hòa',60,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (732,N'Thị xã Long Khánh',60,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (734,N'Huyện Tân Phú',60,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (735,N'Huyện Vĩnh Cửu',60,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (736,N'Huyện Định Quán',60,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (737,N'Huyện Trảng Bom',60,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (738,N'Huyện Thống Nhất',60,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (739,N'Huyện Cẩm Mỹ',60,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (740,N'Huyện Long Thành',60,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (741,N'Huyện Xuân Lộc',60,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (742,N'Huyện Nhơn Trạch',60,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (747,N'Thành phố Vũng Tàu',62,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (748,N'Thành phố Bà Rịa',62,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (750,N'Huyện Châu Đức',62,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (751,N'Huyện Xuyên Mộc',62,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (752,N'Huyện Long Điền',62,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (753,N'Huyện Đất Đỏ',62,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (754,N'Huyện Tân Thành',62,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (755,N'Huyện Côn Đảo',62,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (760,N'Quận 1',1,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (761,N'Quận 12',1,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (762,N'Quận Thủ Đức',1,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (763,N'Quận 9',1,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (764,N'Quận Gò Vấp',1,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (765,N'Quận Bình Thạnh',1,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (766,N'Quận Tân Bình',1,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (767,N'Quận Tân Phú',1,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (768,N'Quận Phú Nhuận',1,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (769,N'Quận 2',1,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (770,N'Quận 3',1,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (771,N'Quận 10',1,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (772,N'Quận 11',1,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (773,N'Quận 4',1,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (774,N'Quận 5',1,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (775,N'Quận 6',1,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (776,N'Quận 8',1,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (777,N'Quận Bình Tân',1,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (778,N'Quận 7',1,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (783,N'Huyện Củ Chi',1,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (784,N'Huyện Hóc Môn',1,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (785,N'Huyện Bình Chánh',1,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (786,N'Huyện Nhà Bè',1,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (787,N'Huyện Cần Giờ',1,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (794,N'Thành phố Tân An',32,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (795,N'Thị xã Kiến Tường',32,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (796,N'Huyện Tân Hưng',32,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (797,N'Huyện Vĩnh Hưng',32,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (798,N'Huyện Mộc Hóa',32,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (799,N'Huyện Tân Thạnh',32,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (800,N'Huyện Thạnh Hóa',32,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (801,N'Huyện Đức Huệ',32,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (802,N'Huyện Đức Hòa',32,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (803,N'Huyện Bến Lức',32,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (804,N'Huyện Thủ Thừa',32,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (805,N'Huyện Tân Trụ',32,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (806,N'Huyện Cần Đước',32,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (807,N'Huyện Cần Giuộc',32,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (808,N'Huyện Châu Thành',32,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (815,N'Thành phố Mỹ Tho',50,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (816,N'Thị xã Gò Công',50,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (817,N'Thị xã Cai Lậy',50,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (818,N'Huyện Tân Phước',50,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (819,N'Huyện Cái Bè',50,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (820,N'Huyện Cai Lậy',50,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (821,N'Huyện Châu Thành',50,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (822,N'Huyện Chợ Gạo',50,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (823,N'Huyện Gò Công Tây',50,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (824,N'Huyện Gò Công Đông',50,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (825,N'Huyện Tân Phú Đông',50,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (829,N'Thành phố Bến Tre',63,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (831,N'Huyện Châu Thành',63,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (832,N'Huyện Chợ Lách',63,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (833,N'Huyện Mỏ Cày Nam',63,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (834,N'Huyện Giồng Trôm',63,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (835,N'Huyện Bình Đại',63,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (836,N'Huyện Ba Tri',63,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (837,N'Huyện Thạnh Phú',63,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (838,N'Huyện Mỏ Cày Bắc',63,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (842,N'Thành phố Trà Vinh',51,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (844,N'Huyện Càng Long',51,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (845,N'Huyện Cầu Kè',51,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (846,N'Huyện Tiểu Cần',51,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (847,N'Huyện Châu Thành',51,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (848,N'Huyện Cầu Ngang',51,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (849,N'Huyện Trà Cú',51,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (850,N'Huyện Duyên Hải',51,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (851,N'Thị xã Duyên Hải',51,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (855,N'Thành phố Vĩnh Long',53,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (857,N'Huyện Long Hồ',53,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (858,N'Huyện Mang Thít',53,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (859,N'Huyện Vũng Liêm',53,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (860,N'Huyện Tam Bình',53,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (861,N'Thị xã Bình Minh',53,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (862,N'Huyện Trà Ôn',53,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (863,N'Huyện Bình Tân',53,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (866,N'Thành phố Cao Lãnh',61,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (867,N'Thành phố Sa Đéc',61,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (868,N'Thị xã Hồng Ngự',61,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (869,N'Huyện Tân Hồng',61,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (870,N'Huyện Hồng Ngự',61,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (871,N'Huyện Tam Nông',61,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (872,N'Huyện Tháp Mười',61,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (873,N'Huyện Cao Lãnh',61,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (874,N'Huyện Thanh Bình',61,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (875,N'Huyện Lấp Vò',61,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (876,N'Huyện Lai Vung',61,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (877,N'Huyện Châu Thành',61,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (883,N'Thành phố Long Xuyên',4,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (884,N'Thành phố Châu Đốc',4,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (886,N'Huyện An Phú',4,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (887,N'Thị xã Tân Châu',4,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (888,N'Huyện Phú Tân',4,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (889,N'Huyện Châu Phú',4,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (890,N'Huyện Tịnh Biên',4,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (891,N'Huyện Tri Tôn',4,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (892,N'Huyện Châu Thành',4,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (893,N'Huyện Chợ Mới',4,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (894,N'Huyện Thoại Sơn',4,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (899,N'Thành phố Rạch Giá',26,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (900,N'Thị xã Hà Tiên',26,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (902,N'Huyện Kiên Lương',26,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (903,N'Huyện Hòn Đất',26,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (904,N'Huyện Tân Hiệp',26,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (905,N'Huyện Châu Thành',26,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (906,N'Huyện Giồng Riềng',26,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (907,N'Huyện Gò Quao',26,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (908,N'Huyện An Biên',26,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (909,N'Huyện An Minh',26,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (910,N'Huyện Vĩnh Thuận',26,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (911,N'Huyện Phú Quốc',26,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (912,N'Huyện Kiên Hải',26,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (913,N'Huyện U Minh Thượng',26,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (914,N'Huyện Giang Thành',26,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (916,N'Quận Ninh Kiều',14,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (917,N'Quận Ô Môn',14,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (918,N'Quận Bình Thuỷ',14,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (919,N'Quận Cái Răng',14,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (923,N'Quận Thốt Nốt',14,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (924,N'Huyện Vĩnh Thạnh',14,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (925,N'Huyện Cờ Đỏ',14,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (926,N'Huyện Phong Điền',14,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (927,N'Huyện Thới Lai',14,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (930,N'Thành phố Vị Thanh',22,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (931,N'Thị xã Ngã Bảy',22,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (932,N'Huyện Châu Thành A',22,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (933,N'Huyện Châu Thành',22,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (934,N'Huyện Phụng Hiệp',22,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (935,N'Huyện Vị Thủy',22,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (936,N'Huyện Long Mỹ',22,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (937,N'Thị xã Long Mỹ',22,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (941,N'Thành phố Sóc Trăng',44,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (942,N'Huyện Châu Thành',44,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (943,N'Huyện Kế Sách',44,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (944,N'Huyện Mỹ Tú',44,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (945,N'Huyện Cù Lao Dung',44,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (946,N'Huyện Long Phú',44,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (947,N'Huyện Mỹ Xuyên',44,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (948,N'Thị xã Ngã Năm',44,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (949,N'Huyện Thạnh Trị',44,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (950,N'Thị xã Vĩnh Châu',44,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (951,N'Huyện Trần Đề',44,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (954,N'Thành phố Bạc Liêu',7,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (956,N'Huyện Hồng Dân',7,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (957,N'Huyện Phước Long',7,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (958,N'Huyện Vĩnh Lợi',7,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (959,N'Thị xã Giá Rai',7,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (960,N'Huyện Đông Hải',7,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (961,N'Huyện Hòa Bình',7,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (964,N'Thành phố Cà Mau',7,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (966,N'Huyện U Minh',7,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (967,N'Huyện Thới Bình',7,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (968,N'Huyện Trần Văn Thời',7,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (969,N'Huyện Cái Nước',7,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (970,N'Huyện Đầm Dơi',7,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (971,N'Huyện Năm Căn',7,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (972,N'Huyện Phú Tân',7,0)
INSERT INTO Districts([Id],[Name],[CityId], [Sort]) VALUES (973,N'Huyện Ngọc Hiển',7,0)