//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ECommerce.Resources.Languages.language", typeof(language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Về Chúng Tôi.
        /// </summary>
        public static string ABOUT_US {
            get {
                return ResourceManager.GetString("ABOUT_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bán Chạy Nhất.
        /// </summary>
        public static string BESTSELLER {
            get {
                return ResourceManager.GetString("BESTSELLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh Mục.
        /// </summary>
        public static string CATEGORY {
            get {
                return ResourceManager.GetString("CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồng Hồ Trẻ Em.
        /// </summary>
        public static string CHILDREN_WATCH {
            get {
                return ResourceManager.GetString("CHILDREN_WATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chương Trình Cộng Tác Viên.
        /// </summary>
        public static string COLLABORATIVE_PROGRAM {
            get {
                return ResourceManager.GetString("COLLABORATIVE_PROGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cộng Tác Viên.
        /// </summary>
        public static string COLLABORATORS {
            get {
                return ResourceManager.GetString("COLLABORATORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông Tin Công Ty.
        /// </summary>
        public static string COMPANY_INFO {
            get {
                return ResourceManager.GetString("COMPANY_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên Hệ.
        /// </summary>
        public static string CONTACT {
            get {
                return ResourceManager.GetString("CONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên Hệ Với Chúng Tôi.
        /// </summary>
        public static string CONTACT_US {
            get {
                return ResourceManager.GetString("CONTACT_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồng Hồ Cặp.
        /// </summary>
        public static string COUPLE_WATCH {
            get {
                return ResourceManager.GetString("COUPLE_WATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng nói gì về chúng tôi?.
        /// </summary>
        public static string CUSTOMER_SAY_ABOUT_US {
            get {
                return ResourceManager.GetString("CUSTOMER_SAY_ABOUT_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao Hàng.
        /// </summary>
        public static string DELIVERY {
            get {
                return ResourceManager.GetString("DELIVERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao Hàng Miễn Phí.
        /// </summary>
        public static string FREE_DELIVERY {
            get {
                return ResourceManager.GetString("FREE_DELIVERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các Câu Hỏi Thường Gặp.
        /// </summary>
        public static string FREQUENTLY_QUESTION {
            get {
                return ResourceManager.GetString("FREQUENTLY_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảo Hành.
        /// </summary>
        public static string GUARANTEE {
            get {
                return ResourceManager.GetString("GUARANTEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang Chủ.
        /// </summary>
        public static string HOME {
            get {
                return ResourceManager.GetString("HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hỗ trợ liên tục cho khách hàng.
        /// </summary>
        public static string HOME_CUSTOMER_SUPPORT {
            get {
                return ResourceManager.GetString("HOME_CUSTOMER_SUPPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TP.HCM và đơn hàng trên 2.000.000 VNĐ.
        /// </summary>
        public static string HOME_FREE_DELIVERY {
            get {
                return ResourceManager.GetString("HOME_FREE_DELIVERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm chất lượng và chính hãng.
        /// </summary>
        public static string HOME_QUALITY_PRODUCTS {
            get {
                return ResourceManager.GetString("HOME_QUALITY_PRODUCTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi Trả Trong 1 Tuần.
        /// </summary>
        public static string HOME_RETURN_PAYMENT_WEEK {
            get {
                return ResourceManager.GetString("HOME_RETURN_PAYMENT_WEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao Dịch An Toàn.
        /// </summary>
        public static string HOME_SECURITY_TRANSACTION {
            get {
                return ResourceManager.GetString("HOME_SECURITY_TRANSACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hỗ Trợ 24/7.
        /// </summary>
        public static string HOME_SUPPORT_247 {
            get {
                return ResourceManager.GetString("HOME_SUPPORT_247", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiên Bản Giới Hạn.
        /// </summary>
        public static string LIMITED_EDITION {
            get {
                return ResourceManager.GetString("LIMITED_EDITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng Nhập.
        /// </summary>
        public static string LOGIN {
            get {
                return ResourceManager.GetString("LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồng Hồ Nam.
        /// </summary>
        public static string MENS_WATCH {
            get {
                return ResourceManager.GetString("MENS_WATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhiều Người Xem Nhất.
        /// </summary>
        public static string MOST_VIEWED {
            get {
                return ResourceManager.GetString("MOST_VIEWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài Khoản Của Tôi.
        /// </summary>
        public static string MY_ACCOUNT {
            get {
                return ResourceManager.GetString("MY_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa Chỉ Của Tôi.
        /// </summary>
        public static string MY_ADDRESS {
            get {
                return ResourceManager.GetString("MY_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số Dư Của Tôi.
        /// </summary>
        public static string MY_BALANCE {
            get {
                return ResourceManager.GetString("MY_BALANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn Hàng Của Tôi.
        /// </summary>
        public static string MY_ORDER {
            get {
                return ResourceManager.GetString("MY_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mới.
        /// </summary>
        public static string NEW {
            get {
                return ResourceManager.GetString("NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mẫu Mới.
        /// </summary>
        public static string NEW_MODEL {
            get {
                return ResourceManager.GetString("NEW_MODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang Giảm Giá.
        /// </summary>
        public static string ON_SALE {
            get {
                return ResourceManager.GetString("ON_SALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh Toán.
        /// </summary>
        public static string PAYMENT {
            get {
                return ResourceManager.GetString("PAYMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chính Sách.
        /// </summary>
        public static string POLICY {
            get {
                return ResourceManager.GetString("POLICY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản Phẩm Được Tìm Nhiều Nhất.
        /// </summary>
        public static string PRODUCTS_ARE_LOOKED_MOST {
            get {
                return ResourceManager.GetString("PRODUCTS_ARE_LOOKED_MOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn Tiền.
        /// </summary>
        public static string REFUND {
            get {
                return ResourceManager.GetString("REFUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trả Hàng.
        /// </summary>
        public static string RETURN {
            get {
                return ResourceManager.GetString("RETURN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giảm Giá.
        /// </summary>
        public static string SALE {
            get {
                return ResourceManager.GetString("SALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dịch Vụ.
        /// </summary>
        public static string SERVICE {
            get {
                return ResourceManager.GetString("SERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các Trang Mạng Xã Hội.
        /// </summary>
        public static string SOCIAL_PAGES {
            get {
                return ResourceManager.GetString("SOCIAL_PAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiên Bản Đặc Biệt.
        /// </summary>
        public static string SPECIAL_VERSION {
            get {
                return ResourceManager.GetString("SPECIAL_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hỗ Trợ.
        /// </summary>
        public static string SUPPORT {
            get {
                return ResourceManager.GetString("SUPPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hỗ Trợ Các Loại Thẻ.
        /// </summary>
        public static string SUPPORT_TYPES_OF_CARDS {
            get {
                return ResourceManager.GetString("SUPPORT_TYPES_OF_CARDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chính sách &amp; Hỗ trợ.
        /// </summary>
        public static string SUPPORTING_POLICIES {
            get {
                return ResourceManager.GetString("SUPPORTING_POLICIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điều khoản và điều kiện.
        /// </summary>
        public static string TEMP_CONDITION {
            get {
                return ResourceManager.GetString("TEMP_CONDITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điều Khoản.
        /// </summary>
        public static string TERM {
            get {
                return ResourceManager.GetString("TERM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thương Hiệu.
        /// </summary>
        public static string TRADEMARK {
            get {
                return ResourceManager.GetString("TRADEMARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem Ngay.
        /// </summary>
        public static string WATCH_NOW {
            get {
                return ResourceManager.GetString("WATCH_NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồng Hồ Nữ.
        /// </summary>
        public static string WOMENS_WATCH {
            get {
                return ResourceManager.GetString("WOMENS_WATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viết Đánh Giá.
        /// </summary>
        public static string WRITE_A_REVIEW {
            get {
                return ResourceManager.GetString("WRITE_A_REVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viết Thư Cho Chúng Tôi.
        /// </summary>
        public static string WRITE_LETTER_TO_US {
            get {
                return ResourceManager.GetString("WRITE_LETTER_TO_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa Chỉ Email Của Bạn.
        /// </summary>
        public static string YOUR_EMAIL_ADDRESS {
            get {
                return ResourceManager.GetString("YOUR_EMAIL_ADDRESS", resourceCulture);
            }
        }
    }
}
