//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ECommerce.Resources.Languages.language", typeof(language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Về Chúng Tôi.
        /// </summary>
        public static string ABOUT_US {
            get {
                return ResourceManager.GetString("ABOUT_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm vào giỏ hàng.
        /// </summary>
        public static string ADD_TO_CART {
            get {
                return ResourceManager.GetString("ADD_TO_CART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string ADDRESS {
            get {
                return ResourceManager.GetString("ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bán Chạy Nhất.
        /// </summary>
        public static string BESTSELLER {
            get {
                return ResourceManager.GetString("BESTSELLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giỏ hàng.
        /// </summary>
        public static string CART {
            get {
                return ResourceManager.GetString("CART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh Mục.
        /// </summary>
        public static string CATEGORY {
            get {
                return ResourceManager.GetString("CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán.
        /// </summary>
        public static string CHECK_OUT {
            get {
                return ResourceManager.GetString("CHECK_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồng Hồ Trẻ Em.
        /// </summary>
        public static string CHILDREN_WATCH {
            get {
                return ResourceManager.GetString("CHILDREN_WATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chương Trình Cộng Tác Viên.
        /// </summary>
        public static string COLLABORATIVE_PROGRAM {
            get {
                return ResourceManager.GetString("COLLABORATIVE_PROGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cộng Tác Viên.
        /// </summary>
        public static string COLLABORATORS {
            get {
                return ResourceManager.GetString("COLLABORATORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông Tin Công Ty.
        /// </summary>
        public static string COMPANY_INFO {
            get {
                return ResourceManager.GetString("COMPANY_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên Hệ.
        /// </summary>
        public static string CONTACT {
            get {
                return ResourceManager.GetString("CONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên Hệ Với Chúng Tôi.
        /// </summary>
        public static string CONTACT_US {
            get {
                return ResourceManager.GetString("CONTACT_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồng Hồ Cặp.
        /// </summary>
        public static string COUPLE_WATCH {
            get {
                return ResourceManager.GetString("COUPLE_WATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        public static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng nói gì về chúng tôi?.
        /// </summary>
        public static string CUSTOMER_SAY_ABOUT_US {
            get {
                return ResourceManager.GetString("CUSTOMER_SAY_ABOUT_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặc tính đồng hồ.
        /// </summary>
        public static string DAC_TINH_DONG_HO {
            get {
                return ResourceManager.GetString("DAC_TINH_DONG_HO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao Hàng.
        /// </summary>
        public static string DELIVERY {
            get {
                return ResourceManager.GetString("DELIVERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đường kính mặt đồng hồ.
        /// </summary>
        public static string DUONG_KINH_MAT_DONG_HO {
            get {
                return ResourceManager.GetString("DUONG_KINH_MAT_DONG_HO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BỘ LỌC.
        /// </summary>
        public static string FILTER {
            get {
                return ResourceManager.GetString("FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao Hàng Miễn Phí.
        /// </summary>
        public static string FREE_DELIVERY {
            get {
                return ResourceManager.GetString("FREE_DELIVERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các Câu Hỏi Thường Gặp.
        /// </summary>
        public static string FREQUENTLY_QUESTION {
            get {
                return ResourceManager.GetString("FREQUENTLY_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảo Hành.
        /// </summary>
        public static string GUARANTEE {
            get {
                return ResourceManager.GetString("GUARANTEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi cho bạn.
        /// </summary>
        public static string GUI_CHO_BAN {
            get {
                return ResourceManager.GetString("GUI_CHO_BAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang Chủ.
        /// </summary>
        public static string HOME {
            get {
                return ResourceManager.GetString("HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hỗ trợ liên tục cho khách hàng.
        /// </summary>
        public static string HOME_CUSTOMER_SUPPORT {
            get {
                return ResourceManager.GetString("HOME_CUSTOMER_SUPPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TP.HCM và đơn hàng trên 2.000.000 VNĐ.
        /// </summary>
        public static string HOME_FREE_DELIVERY {
            get {
                return ResourceManager.GetString("HOME_FREE_DELIVERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao Hàng Miễn Phí.
        /// </summary>
        public static string HOME_FREE_DELIVERY_1 {
            get {
                return ResourceManager.GetString("HOME_FREE_DELIVERY_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm chất lượng và chính hãng.
        /// </summary>
        public static string HOME_QUALITY_PRODUCTS {
            get {
                return ResourceManager.GetString("HOME_QUALITY_PRODUCTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi Trả Trong 1 Tuần.
        /// </summary>
        public static string HOME_RETURN_PAYMENT_WEEK {
            get {
                return ResourceManager.GetString("HOME_RETURN_PAYMENT_WEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cam Kết Hoàn Tiền.
        /// </summary>
        public static string HOME_RETURN_PAYMENT_WEEK_1 {
            get {
                return ResourceManager.GetString("HOME_RETURN_PAYMENT_WEEK_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao Dịch An Toàn.
        /// </summary>
        public static string HOME_SECURITY_TRANSACTION {
            get {
                return ResourceManager.GetString("HOME_SECURITY_TRANSACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm chất lượng và chính hãng.
        /// </summary>
        public static string HOME_SECURITY_TRANSACTION_1 {
            get {
                return ResourceManager.GetString("HOME_SECURITY_TRANSACTION_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hỗ Trợ 24/7.
        /// </summary>
        public static string HOME_SUPPORT_247 {
            get {
                return ResourceManager.GetString("HOME_SUPPORT_247", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hỗ trợ liên tục cho khách hàng.
        /// </summary>
        public static string HOME_SUPPORT_247_1 {
            get {
                return ResourceManager.GetString("HOME_SUPPORT_247_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiên Bản Giới Hạn.
        /// </summary>
        public static string LIMITED_EDITION {
            get {
                return ResourceManager.GetString("LIMITED_EDITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại dây.
        /// </summary>
        public static string LOAI_DAY {
            get {
                return ResourceManager.GetString("LOAI_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại niềng.
        /// </summary>
        public static string LOAI_NIENG {
            get {
                return ResourceManager.GetString("LOAI_NIENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng Nhập.
        /// </summary>
        public static string LOGIN {
            get {
                return ResourceManager.GetString("LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lựa chọn.
        /// </summary>
        public static string LUA_CHON {
            get {
                return ResourceManager.GetString("LUA_CHON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã sản phẩm.
        /// </summary>
        public static string MA_SAN_PHAM {
            get {
                return ResourceManager.GetString("MA_SAN_PHAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại máy.
        /// </summary>
        public static string MACHINE_TYPE {
            get {
                return ResourceManager.GetString("MACHINE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Màu.
        /// </summary>
        public static string MAU {
            get {
                return ResourceManager.GetString("MAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Màu mặt kính.
        /// </summary>
        public static string MAU_MAT_KINH {
            get {
                return ResourceManager.GetString("MAU_MAT_KINH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồng Hồ Nam.
        /// </summary>
        public static string MENS_WATCH {
            get {
                return ResourceManager.GetString("MENS_WATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhiều Người Xem Nhất.
        /// </summary>
        public static string MOST_VIEWED {
            get {
                return ResourceManager.GetString("MOST_VIEWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài Khoản Của Tôi.
        /// </summary>
        public static string MY_ACCOUNT {
            get {
                return ResourceManager.GetString("MY_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa Chỉ Của Tôi.
        /// </summary>
        public static string MY_ADDRESS {
            get {
                return ResourceManager.GetString("MY_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số Dư Của Tôi.
        /// </summary>
        public static string MY_BALANCE {
            get {
                return ResourceManager.GetString("MY_BALANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn Hàng Của Tôi.
        /// </summary>
        public static string MY_ORDER {
            get {
                return ResourceManager.GetString("MY_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mới.
        /// </summary>
        public static string NEW {
            get {
                return ResourceManager.GetString("NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mẫu Mới.
        /// </summary>
        public static string NEW_MODEL {
            get {
                return ResourceManager.GetString("NEW_MODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm mới.
        /// </summary>
        public static string NEW_PRODUCT {
            get {
                return ResourceManager.GetString("NEW_PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếp.
        /// </summary>
        public static string NEXT {
            get {
                return ResourceManager.GetString("NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nơi sản xuất.
        /// </summary>
        public static string NOI_SAN_XUAT {
            get {
                return ResourceManager.GetString("NOI_SAN_XUAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang Giảm Giá.
        /// </summary>
        public static string ON_SALE {
            get {
                return ResourceManager.GetString("ON_SALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh Toán.
        /// </summary>
        public static string PAYMENT {
            get {
                return ResourceManager.GetString("PAYMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SĐT.
        /// </summary>
        public static string PHONE {
            get {
                return ResourceManager.GetString("PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phong cách.
        /// </summary>
        public static string PHUONG_CACH {
            get {
                return ResourceManager.GetString("PHUONG_CACH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chính Sách.
        /// </summary>
        public static string POLICY {
            get {
                return ResourceManager.GetString("POLICY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trở lại.
        /// </summary>
        public static string PREVIOUS {
            get {
                return ResourceManager.GetString("PREVIOUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá.
        /// </summary>
        public static string PRICE {
            get {
                return ResourceManager.GetString("PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sản phẩm.
        /// </summary>
        public static string PRODUCT {
            get {
                return ResourceManager.GetString("PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên sản phẩm.
        /// </summary>
        public static string PRODUCT_NAME {
            get {
                return ResourceManager.GetString("PRODUCT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản Phẩm Được Tìm Nhiều Nhất.
        /// </summary>
        public static string PRODUCTS_ARE_LOOKED_MOST {
            get {
                return ResourceManager.GetString("PRODUCTS_ARE_LOOKED_MOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn Tiền.
        /// </summary>
        public static string REFUND {
            get {
                return ResourceManager.GetString("REFUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        public static string REGISTER {
            get {
                return ResourceManager.GetString("REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trả Hàng.
        /// </summary>
        public static string RETURN {
            get {
                return ResourceManager.GetString("RETURN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đánh giá.
        /// </summary>
        public static string REVIEW {
            get {
                return ResourceManager.GetString("REVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHẢN HỒI CỦA KHÁCH.
        /// </summary>
        public static string REVIEW_FROM_USER {
            get {
                return ResourceManager.GetString("REVIEW_FROM_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giảm Giá.
        /// </summary>
        public static string SALE {
            get {
                return ResourceManager.GetString("SALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        public static string SEARCH {
            get {
                return ResourceManager.GetString("SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem Thêm.
        /// </summary>
        public static string SEE_MORE {
            get {
                return ResourceManager.GetString("SEE_MORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi.
        /// </summary>
        public static string SEND {
            get {
                return ResourceManager.GetString("SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dịch Vụ.
        /// </summary>
        public static string SERVICE {
            get {
                return ResourceManager.GetString("SERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiện.
        /// </summary>
        public static string SHOW {
            get {
                return ResourceManager.GetString("SHOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        public static string SO_LUONG {
            get {
                return ResourceManager.GetString("SO_LUONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các trang xã hội.
        /// </summary>
        public static string SOCIAL_PAGE {
            get {
                return ResourceManager.GetString("SOCIAL_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các Trang Mạng Xã Hội.
        /// </summary>
        public static string SOCIAL_PAGES {
            get {
                return ResourceManager.GetString("SOCIAL_PAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiên Bản Đặc Biệt.
        /// </summary>
        public static string SPECIAL_VERSION {
            get {
                return ResourceManager.GetString("SPECIAL_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hỗ Trợ.
        /// </summary>
        public static string SUPPORT {
            get {
                return ResourceManager.GetString("SUPPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hỗ Trợ Các Loại Thẻ.
        /// </summary>
        public static string SUPPORT_TYPES_OF_CARDS {
            get {
                return ResourceManager.GetString("SUPPORT_TYPES_OF_CARDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chính sách &amp; Hỗ trợ.
        /// </summary>
        public static string SUPPORTING_POLICIES {
            get {
                return ResourceManager.GetString("SUPPORTING_POLICIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điều khoản và điều kiện.
        /// </summary>
        public static string TEMP_CONDITION {
            get {
                return ResourceManager.GetString("TEMP_CONDITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điều Khoản.
        /// </summary>
        public static string TERM {
            get {
                return ResourceManager.GetString("TERM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian bảo hành ở cửa hàng.
        /// </summary>
        public static string THOI_GIAN_BAO_HANH_O_CUA_HANG {
            get {
                return ResourceManager.GetString("THOI_GIAN_BAO_HANH_O_CUA_HANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian bảo hành quốc tế.
        /// </summary>
        public static string THOI_GIAN_BAO_HANH_QUOC_TE {
            get {
                return ResourceManager.GetString("THOI_GIAN_BAO_HANH_QUOC_TE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin chống thấm.
        /// </summary>
        public static string THONG_TIN_CHONG_THAM {
            get {
                return ResourceManager.GetString("THONG_TIN_CHONG_THAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng cộng.
        /// </summary>
        public static string TOTAL {
            get {
                return ResourceManager.GetString("TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thương Hiệu.
        /// </summary>
        public static string TRADEMARK {
            get {
                return ResourceManager.GetString("TRADEMARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string TRANG_THAI {
            get {
                return ResourceManager.GetString("TRANG_THAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem Ngay.
        /// </summary>
        public static string WATCH_NOW {
            get {
                return ResourceManager.GetString("WATCH_NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồng Hồ Nữ.
        /// </summary>
        public static string WOMENS_WATCH {
            get {
                return ResourceManager.GetString("WOMENS_WATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viết Đánh Giá.
        /// </summary>
        public static string WRITE_A_REVIEW {
            get {
                return ResourceManager.GetString("WRITE_A_REVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viết Thư Cho Chúng Tôi.
        /// </summary>
        public static string WRITE_LETTER_TO_US {
            get {
                return ResourceManager.GetString("WRITE_LETTER_TO_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa Chỉ Email Của Bạn.
        /// </summary>
        public static string YOUR_EMAIL_ADDRESS {
            get {
                return ResourceManager.GetString("YOUR_EMAIL_ADDRESS", resourceCulture);
            }
        }
    }
}
